### ISSUE TITLE
Setting up Continuous Integration

### ISSUE THREAD

**Issue by michzimny** [sciencemesh/cs3api4lab#29]
Let's set up CI for this repository. We can do this in two steps:
1. Automatic Docker builds and publishing of images, together with marking commits/PRs as succeeded or not.
2. Running (integration?) tests during the CI process (perhaps as another issue?).

Possible implementations, based on my experience:

1. [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions) and [GitHub container registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry) - native solution from GitHub, suggested by GitHub. It's a beta.

2. [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions) and [GitHub package registry](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages) - as above but this one is more mature, however [it does not allow to anonymously pull images](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358), so it's a pain for development and local app instances.

3. [Builds in Docker Hub](https://docs.docker.com/docker-hub/builds/) - most commonly used for publishing images, not necessarily for CI. It's a 3rd-party solution. There are some issues with this integration such as accessing build details from GitHub user interface. To my knowledge, in this approach, we couldn't run tests. This approach needs to be set up by GitHub organization's administrators, giving the Docker Hub high priviliges to the organization.

4. [Travis CI](https://travis-ci.org/) for CI with images being published in Docker Hub - To my experience, a commonly-used solution for CI in GitHub for years (esp. before GitHub Actions were introduced). This approach is based on the two 3rd-party solutions.

I would go for no. 1 (suggested by GitHub) or 4 (a common one).

cc @diocas

**Comment by diocas** [comment]
I would say that more importantly than building the docker image is publishing the extension (to PyPi). This Docker image is mainly for testing and extension will be integrated with the images that we (SWAN, JRC, PSNC?) and others already have and this won't be used.

I would vote in using Github action for the pipelines (whatever the repo we use.. Even Docker hub, since we can store secrets).
As for the repo, we also have the option of using https://quay.io/

**Comment by michzimny** [comment]
I see we more or less agree for solution no. 1, which might be also an easy one.

In brief, I would say that the main goal is to have CI, and docker images are useful side effect. If we offer a Dockerfile in this repo, one of CI steps should be validating for every commit whether the corresponding docker image builds up properly. And if we had a docker image already built during CI, I would rather publish it anywhere to ease development instead of abandon it.

**Comment by diocas** [comment]
Yes, we agree on proposal 1, so let's go for it.
But I not so sure about validating PRs with building the image as a step (seems unnecessary)...

I would say that PRs should be validated, but this means building the python wheels and running the tests  [+ (in the future) the same for the lab extension].
Then, when we merge into master, we build the docker image. If this fails, it's because we had a problem with the image and not the extension (as the extension was checked before merging). And that should be it.
I would tag this with the a dev tag or something similar.

Then, when a tag is created, we build and publish the python wheels to Pypi + build and tag a docker image (version + latest tags) [ + (in the future) build and push to NPM the lab extension].

I would use bump2version (manually, locally) to have the versions synced across the python module and the js code. Like we do in our swan extensions: https://github.com/swan-cern/jupyter-extensions/blob/master/.github/workflows/swan-ci-ca.yml (the extra steps/configs are due to our monorepo organization).

What do you think?

**Comment by michzimny** [comment]
>  Then, when we merge into master, we build the docker image. If this fails, it's because we had a problem with the image and not the extension 

Not necessarily. Recently, we had that issue of deleted files, so the image could not have been built (#25). It would be useful to observe such issues as soon as possible (i.e. before PRs is merged).

If a repo contained a Python library, a JS library, and a Docker image, I find it valuable to validate all the three resources before PR is merged. What is the advantage of validating only some of them? It's processing time, perhaps, but it's rather a small advantage.

I'm fine with the rest of your comment.

**Comment by diocas** [comment]
Ok, let's do all then.

**Comment by diocas** [comment]
Any update on this?

**Comment by michzimny** [comment]
Perhaps it's no longer Jarek who should be assigned. No idea who.

**Comment by michzimny** [comment]
I think it can be closed thanks to #106.

**Comment by diocas** [comment]
Not really, we still need to set up a pipeline to publish the extension to pypi. And even the docker image, we should build the latest master and push it (I was going to ask you to do that in the PR, but I don't think is urgent)
